
      # The name of this app. Must be unique within a project.
name: lnclass

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Ruby documentation
# (https://docs.platform.sh/languages/ruby.html#supported-versions)
# to find the supported versions for the 'ruby' type.
type: 'ruby:3.0'
      

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
    postgresdatabase: 'dbpostgres:postgresql'


hooks:
    build: |
      gem install bundler:2.2.33
      bundle install
      
    deploy: |
      RACK_ENV=production bundle exec rake db:migrate


# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at. 


mounts:
    "/log":
        source: local
        source_path: log
    "/storage":
        source: local
        source_path: storage
    "/tmp":
        source: local
        source_path: tmp

web:
    upstream:
        socket_family: unix
    commands:
        start: "bundle exec unicorn -l $SOCKET"

    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h
            allow: true

    
disk: 1024
