  AddCourse[m
  AddExercices[m
  AddLevelAndMaterial[m
  AnswerFix[m
  Bootstrap[m
  ClassAdmin[m
  Classroom[m
  Dashbaord[m
  Develop[m
  Enrollment[m
  ExerciceDesign[m
  ExerciceShowInClassroom[m
  FixSignIn[m
  Friendly[m
  Herokuapp[m
  HomePage[m
  Membership[m
  MyDashboard[m
* [32mNavBar[m
  QuestionsAndAnswers[m
  StudentSignUp[m
  Tailwindcss[m
  UUID[m
  main[m
